---
manager:
  # We need this tto add a PR comment
  plan_outputs:
    html:
      class: octodns.provider.plan.PlanHtml
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    default_ttl: 300
    directory: zones
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN
zones:
  dorns.fr.:
    sources:
      - config
    targets:
      - cloudflare
  o1.vc.:
    sources:
      - config
    targets:
      - cloudflare
