
name: Validate DNS records

on:
  pull_request:
  
jobs:
  check:
    name: Run `octodns-sync` with config.yaml
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.generate-plan.outputs.plan }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@v3.0.1
        id: generate-plan
        with:
          config_path: config.yaml
          add_pr_comment: "Yes"
          pr_comment_token: '${{ github.token }}'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        
